### ISSUE TITLE
Kay but how do I use this?

### ISSUE THREAD

**Issue by ipoopedmypantsuups** [zacharee/WiFiList#1]
Do I need to compile it myself?

**Comment by drogga** [comment]
@ipoopedmypantsuups
Either get it from PS [Paid] https://play.google.com/store/apps/details?id=tk.zwander.wifilist
or build it yourself, fair if you ask, or it it would've if it actually wanted to build and didn't error-out.

@zacharee - Can you please advise \ help ?
https://github.com/drogga/WiFiList/actions/runs/3304226547/jobs/5453205056#step:5:105
Thanks in advance.

**Comment by 18877761327** [comment]
> Do I need to compile it myself?

``
