### ISSUE TITLE
All WPA/WPA2 networks are duplicated as WPA3

### ISSUE THREAD

**Issue by ErrrorMaxx** [zacharee/WiFiList#3]
![Screenshot_20240211-091404](https://github.com/zacharee/WiFiList/assets/30185766/2dca6b2c-ad1a-416a-a078-9c37a8011823)

**Comment by zacharee** [comment]
From what I can tell, Android creates two separate configurations for networks in WPA2/WPA3 Transition Mode.

**Comment by ErrrorMaxx** [comment]
I never connected to any WPA3 or WPA2/WPA3 networks, there are just no such networks available to me.
So even clear WPA2 networks duplicated as WPA/WPA2 and WPA3 networks?

Initially forgot to add: In WiFiList 1.2.1 version there was no duplicates, if this is revelant

**Comment by zacharee** [comment]
In 1.3.0, I changed the filtering on the list provided by Android to be based on the key Android gives to each saved configuration. That means if it's in the list, there's a corresponding saved network in the Android system.

**Comment by ErrrorMaxx** [comment]
Ok, thanks for the explanations. I am closing this issue as this seems to be Android's behaviour, not WiFiList bug
