### ISSUE TITLE
build error in gradle

### ISSUE THREAD

**Issue by Manos654764** [zacharee/WiFiList#4]
every time i try to build the apk, it fails.
i even updated the AGP but it still doesn't work.
heres what it says: "e: file:///C:/Users/xxxx/StudioProjects/WiFiList/app/src/main/java/tk/zwander/wifilist/data/ExportChoice.kt:68:19 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type OutputStream?"

**Comment by zacharee** [comment]
You should be able to build now.
